import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

const config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#3f474d",
        "tertiary-fixed-dim": "#f57ca5",
        "on-background": "#e2e2e6",
        "tertiary-fixed": "#ff8db2",
        "on-secondary": "rgb(var(--color-on-secondary-rgb) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary-rgb) / <alpha-value>)",
        background: "rgb(var(--color-background-rgb) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--color-surface-container-lowest-rgb) / <alpha-value>)",
        "surface-tint": "rgb(var(--color-surface-tint-rgb) / <alpha-value>)",
        "surface-container-high": "rgb(var(--color-surface-container-high-rgb) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--color-on-secondary-container-rgb) / <alpha-value>)",
        "on-secondary-fixed-variant": "#4e5c71",
        "tertiary-container": "rgb(var(--color-tertiary-container-rgb) / <alpha-value>)",
        "secondary-container": "rgb(var(--color-secondary-container-rgb) / <alpha-value>)",
        "surface-bright": "#36393c",
        "on-primary": "rgb(var(--color-on-primary-rgb) / <alpha-value>)",
        tertiary: "rgb(var(--color-tertiary-rgb) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant-rgb) / <alpha-value>)",
        surface: "rgb(var(--color-surface-rgb) / <alpha-value>)",
        "primary-fixed": "#7dd3fc",
        error: "#ffb4ab",
        "primary-dim": "#38bdf8",
        "tertiary-dim": "#ffb2be",
        "surface-container-low": "rgb(var(--color-surface-container-low-rgb) / <alpha-value>)",
        "on-tertiary": "rgb(var(--color-on-tertiary-rgb) / <alpha-value>)",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#0a1d32",
        "on-primary-fixed-variant": "#0ea5e9",
        "on-primary-fixed": "#000000",
        "secondary-fixed": "#d5e3fc",
        "error-dim": "#ffb4ab",
        "inverse-surface": "#e2e2e6",
        "secondary-dim": "#bfc8da",
        "on-primary-container": "rgb(var(--color-on-primary-container-rgb) / <alpha-value>)",
        "surface-container": "rgb(var(--color-surface-container-rgb) / <alpha-value>)",
        "on-error": "#690005",
        "error-container": "#93000a",
        "inverse-primary": "#0284c7",
        "primary-fixed-dim": "#7dd3fc",
        outline: "rgb(var(--color-outline-rgb) / <alpha-value>)",
        "on-surface": "rgb(var(--color-on-surface-rgb) / <alpha-value>)",
        "surface-variant": "rgb(var(--color-surface-variant-rgb) / <alpha-value>)",
        primary: "rgb(var(--color-primary-rgb) / <alpha-value>)",
        "surface-dim": "rgb(var(--color-surface-dim-rgb) / <alpha-value>)",
        "inverse-on-surface": "#2c2f31",
        "on-tertiary-fixed-variant": "#ff8db2",
        "on-tertiary-fixed": "#000000",
        "primary-container": "rgb(var(--color-primary-container-rgb) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--color-surface-container-highest-rgb) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--color-on-tertiary-container-rgb) / <alpha-value>)",
        "secondary-fixed-dim": "#bfc8da",
      },
      fontFamily: {
        headline: "var(--font-grotesk)",
        body: "var(--font-inter)",
        label: "var(--font-inter)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [forms, containerQueries],
} satisfies Config;

export default config;
